/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProtocolsRouteImport } from './routes/_authenticated/protocols'
import { Route as AuthenticatedExtractRouteImport } from './routes/_authenticated/extract'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedExtractIndexRouteImport } from './routes/_authenticated/extract.index'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases.index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as ApiToolsPubmedRouteImport } from './routes/api/tools/pubmed'
import { Route as ApiToolsProviderRouteImport } from './routes/api/tools/provider'
import { Route as ApiToolsInteractionsRouteImport } from './routes/api/tools/interactions'
import { Route as ApiToolsIcdRouteImport } from './routes/api/tools/icd'
import { Route as ApiToolsDrugRouteImport } from './routes/api/tools/drug'
import { Route as AuthenticatedToolsPubmedRouteImport } from './routes/_authenticated/tools.pubmed'
import { Route as AuthenticatedToolsProviderRouteImport } from './routes/_authenticated/tools.provider'
import { Route as AuthenticatedToolsIcdRouteImport } from './routes/_authenticated/tools.icd'
import { Route as AuthenticatedToolsDrugRouteImport } from './routes/_authenticated/tools.drug'
import { Route as AuthenticatedExtractExtractionIdRouteImport } from './routes/_authenticated/extract.$extractionId'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated/cases.$caseId'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolsRoute = AuthenticatedProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractRoute = AuthenticatedExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractIndexRoute =
  AuthenticatedExtractIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExtractRoute,
  } as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCasesRoute,
} as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const ApiToolsPubmedRoute = ApiToolsPubmedRouteImport.update({
  id: '/api/tools/pubmed',
  path: '/api/tools/pubmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsProviderRoute = ApiToolsProviderRouteImport.update({
  id: '/api/tools/provider',
  path: '/api/tools/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsInteractionsRoute = ApiToolsInteractionsRouteImport.update({
  id: '/api/tools/interactions',
  path: '/api/tools/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsIcdRoute = ApiToolsIcdRouteImport.update({
  id: '/api/tools/icd',
  path: '/api/tools/icd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsDrugRoute = ApiToolsDrugRouteImport.update({
  id: '/api/tools/drug',
  path: '/api/tools/drug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsPubmedRoute =
  AuthenticatedToolsPubmedRouteImport.update({
    id: '/tools/pubmed',
    path: '/tools/pubmed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsProviderRoute =
  AuthenticatedToolsProviderRouteImport.update({
    id: '/tools/provider',
    path: '/tools/provider',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsIcdRoute = AuthenticatedToolsIcdRouteImport.update({
  id: '/tools/icd',
  path: '/tools/icd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsDrugRoute = AuthenticatedToolsDrugRouteImport.update({
  id: '/tools/drug',
  path: '/tools/drug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractExtractionIdRoute =
  AuthenticatedExtractExtractionIdRouteImport.update({
    id: '/$extractionId',
    path: '/$extractionId',
    getParentRoute: () => AuthenticatedExtractRoute,
  } as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedCasesRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/cases': typeof AuthenticatedCasesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extract': typeof AuthenticatedExtractRouteWithChildren
  '/protocols': typeof AuthenticatedProtocolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/extract/$extractionId': typeof AuthenticatedExtractExtractionIdRoute
  '/tools/drug': typeof AuthenticatedToolsDrugRoute
  '/tools/icd': typeof AuthenticatedToolsIcdRoute
  '/tools/provider': typeof AuthenticatedToolsProviderRoute
  '/tools/pubmed': typeof AuthenticatedToolsPubmedRoute
  '/api/tools/drug': typeof ApiToolsDrugRoute
  '/api/tools/icd': typeof ApiToolsIcdRoute
  '/api/tools/interactions': typeof ApiToolsInteractionsRoute
  '/api/tools/provider': typeof ApiToolsProviderRoute
  '/api/tools/pubmed': typeof ApiToolsPubmedRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/extract/': typeof AuthenticatedExtractIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/protocols': typeof AuthenticatedProtocolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/extract/$extractionId': typeof AuthenticatedExtractExtractionIdRoute
  '/tools/drug': typeof AuthenticatedToolsDrugRoute
  '/tools/icd': typeof AuthenticatedToolsIcdRoute
  '/tools/provider': typeof AuthenticatedToolsProviderRoute
  '/tools/pubmed': typeof AuthenticatedToolsPubmedRoute
  '/api/tools/drug': typeof ApiToolsDrugRoute
  '/api/tools/icd': typeof ApiToolsIcdRoute
  '/api/tools/interactions': typeof ApiToolsInteractionsRoute
  '/api/tools/provider': typeof ApiToolsProviderRoute
  '/api/tools/pubmed': typeof ApiToolsPubmedRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/extract': typeof AuthenticatedExtractIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/cases': typeof AuthenticatedCasesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extract': typeof AuthenticatedExtractRouteWithChildren
  '/_authenticated/protocols': typeof AuthenticatedProtocolsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/_authenticated/extract/$extractionId': typeof AuthenticatedExtractExtractionIdRoute
  '/_authenticated/tools/drug': typeof AuthenticatedToolsDrugRoute
  '/_authenticated/tools/icd': typeof AuthenticatedToolsIcdRoute
  '/_authenticated/tools/provider': typeof AuthenticatedToolsProviderRoute
  '/_authenticated/tools/pubmed': typeof AuthenticatedToolsPubmedRoute
  '/api/tools/drug': typeof ApiToolsDrugRoute
  '/api/tools/icd': typeof ApiToolsIcdRoute
  '/api/tools/interactions': typeof ApiToolsInteractionsRoute
  '/api/tools/provider': typeof ApiToolsProviderRoute
  '/api/tools/pubmed': typeof ApiToolsPubmedRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/extract/': typeof AuthenticatedExtractIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/extract'
    | '/protocols'
    | '/settings'
    | '/assistant/$threadId'
    | '/cases/$caseId'
    | '/extract/$extractionId'
    | '/tools/drug'
    | '/tools/icd'
    | '/tools/provider'
    | '/tools/pubmed'
    | '/api/tools/drug'
    | '/api/tools/icd'
    | '/api/tools/interactions'
    | '/api/tools/provider'
    | '/api/tools/pubmed'
    | '/assistant/'
    | '/cases/'
    | '/extract/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/protocols'
    | '/settings'
    | '/assistant/$threadId'
    | '/cases/$caseId'
    | '/extract/$extractionId'
    | '/tools/drug'
    | '/tools/icd'
    | '/tools/provider'
    | '/tools/pubmed'
    | '/api/tools/drug'
    | '/api/tools/icd'
    | '/api/tools/interactions'
    | '/api/tools/provider'
    | '/api/tools/pubmed'
    | '/assistant'
    | '/cases'
    | '/extract'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/cases'
    | '/_authenticated/dashboard'
    | '/_authenticated/extract'
    | '/_authenticated/protocols'
    | '/_authenticated/settings'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/cases/$caseId'
    | '/_authenticated/extract/$extractionId'
    | '/_authenticated/tools/drug'
    | '/_authenticated/tools/icd'
    | '/_authenticated/tools/provider'
    | '/_authenticated/tools/pubmed'
    | '/api/tools/drug'
    | '/api/tools/icd'
    | '/api/tools/interactions'
    | '/api/tools/provider'
    | '/api/tools/pubmed'
    | '/_authenticated/assistant/'
    | '/_authenticated/cases/'
    | '/_authenticated/extract/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiToolsDrugRoute: typeof ApiToolsDrugRoute
  ApiToolsIcdRoute: typeof ApiToolsIcdRoute
  ApiToolsInteractionsRoute: typeof ApiToolsInteractionsRoute
  ApiToolsProviderRoute: typeof ApiToolsProviderRoute
  ApiToolsPubmedRoute: typeof ApiToolsPubmedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocols': {
      id: '/_authenticated/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof AuthenticatedProtocolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extract': {
      id: '/_authenticated/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof AuthenticatedExtractRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extract/': {
      id: '/_authenticated/extract/'
      path: '/'
      fullPath: '/extract/'
      preLoaderRoute: typeof AuthenticatedExtractIndexRouteImport
      parentRoute: typeof AuthenticatedExtractRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedCasesRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/api/tools/pubmed': {
      id: '/api/tools/pubmed'
      path: '/api/tools/pubmed'
      fullPath: '/api/tools/pubmed'
      preLoaderRoute: typeof ApiToolsPubmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/provider': {
      id: '/api/tools/provider'
      path: '/api/tools/provider'
      fullPath: '/api/tools/provider'
      preLoaderRoute: typeof ApiToolsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/interactions': {
      id: '/api/tools/interactions'
      path: '/api/tools/interactions'
      fullPath: '/api/tools/interactions'
      preLoaderRoute: typeof ApiToolsInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/icd': {
      id: '/api/tools/icd'
      path: '/api/tools/icd'
      fullPath: '/api/tools/icd'
      preLoaderRoute: typeof ApiToolsIcdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/drug': {
      id: '/api/tools/drug'
      path: '/api/tools/drug'
      fullPath: '/api/tools/drug'
      preLoaderRoute: typeof ApiToolsDrugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/pubmed': {
      id: '/_authenticated/tools/pubmed'
      path: '/tools/pubmed'
      fullPath: '/tools/pubmed'
      preLoaderRoute: typeof AuthenticatedToolsPubmedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/provider': {
      id: '/_authenticated/tools/provider'
      path: '/tools/provider'
      fullPath: '/tools/provider'
      preLoaderRoute: typeof AuthenticatedToolsProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/icd': {
      id: '/_authenticated/tools/icd'
      path: '/tools/icd'
      fullPath: '/tools/icd'
      preLoaderRoute: typeof AuthenticatedToolsIcdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/drug': {
      id: '/_authenticated/tools/drug'
      path: '/tools/drug'
      fullPath: '/tools/drug'
      preLoaderRoute: typeof AuthenticatedToolsDrugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extract/$extractionId': {
      id: '/_authenticated/extract/$extractionId'
      path: '/$extractionId'
      fullPath: '/extract/$extractionId'
      preLoaderRoute: typeof AuthenticatedExtractExtractionIdRouteImport
      parentRoute: typeof AuthenticatedExtractRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedCasesRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
  }
}

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedCasesRouteChildren {
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedCasesRouteChildren: AuthenticatedCasesRouteChildren = {
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedCasesRouteWithChildren =
  AuthenticatedCasesRoute._addFileChildren(AuthenticatedCasesRouteChildren)

interface AuthenticatedExtractRouteChildren {
  AuthenticatedExtractExtractionIdRoute: typeof AuthenticatedExtractExtractionIdRoute
  AuthenticatedExtractIndexRoute: typeof AuthenticatedExtractIndexRoute
}

const AuthenticatedExtractRouteChildren: AuthenticatedExtractRouteChildren = {
  AuthenticatedExtractExtractionIdRoute: AuthenticatedExtractExtractionIdRoute,
  AuthenticatedExtractIndexRoute: AuthenticatedExtractIndexRoute,
}

const AuthenticatedExtractRouteWithChildren =
  AuthenticatedExtractRoute._addFileChildren(AuthenticatedExtractRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtractRoute: typeof AuthenticatedExtractRouteWithChildren
  AuthenticatedProtocolsRoute: typeof AuthenticatedProtocolsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsDrugRoute: typeof AuthenticatedToolsDrugRoute
  AuthenticatedToolsIcdRoute: typeof AuthenticatedToolsIcdRoute
  AuthenticatedToolsProviderRoute: typeof AuthenticatedToolsProviderRoute
  AuthenticatedToolsPubmedRoute: typeof AuthenticatedToolsPubmedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedCasesRoute: AuthenticatedCasesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtractRoute: AuthenticatedExtractRouteWithChildren,
  AuthenticatedProtocolsRoute: AuthenticatedProtocolsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsDrugRoute: AuthenticatedToolsDrugRoute,
  AuthenticatedToolsIcdRoute: AuthenticatedToolsIcdRoute,
  AuthenticatedToolsProviderRoute: AuthenticatedToolsProviderRoute,
  AuthenticatedToolsPubmedRoute: AuthenticatedToolsPubmedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiToolsDrugRoute: ApiToolsDrugRoute,
  ApiToolsIcdRoute: ApiToolsIcdRoute,
  ApiToolsInteractionsRoute: ApiToolsInteractionsRoute,
  ApiToolsProviderRoute: ApiToolsProviderRoute,
  ApiToolsPubmedRoute: ApiToolsPubmedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
