/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProtocolsRouteImport } from './routes/_authenticated/protocols'
import { Route as AuthenticatedExtractRouteImport } from './routes/_authenticated/extract'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolsRoute = AuthenticatedProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractRoute = AuthenticatedExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extract': typeof AuthenticatedExtractRoute
  '/protocols': typeof AuthenticatedProtocolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extract': typeof AuthenticatedExtractRoute
  '/protocols': typeof AuthenticatedProtocolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extract': typeof AuthenticatedExtractRoute
  '/_authenticated/protocols': typeof AuthenticatedProtocolsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/extract'
    | '/protocols'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/extract'
    | '/protocols'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/cases'
    | '/_authenticated/dashboard'
    | '/_authenticated/extract'
    | '/_authenticated/protocols'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocols': {
      id: '/_authenticated/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof AuthenticatedProtocolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extract': {
      id: '/_authenticated/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof AuthenticatedExtractRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtractRoute: typeof AuthenticatedExtractRoute
  AuthenticatedProtocolsRoute: typeof AuthenticatedProtocolsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtractRoute: AuthenticatedExtractRoute,
  AuthenticatedProtocolsRoute: AuthenticatedProtocolsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
